version: "3.1"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: extravios
    ports:
      - "3307:3306"
    volumes:
      - C:/Users/Martin Acosta/Documents/dev/MySQL-Snippets/extravios.sql:/extravios.sql
